export async function GET() {
    return new Response(
        `
        <?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://www.elitasmakina.com/</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/products</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/aboutus</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/contact</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/buhar/4-cikisli</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/buhar/3-cikisli</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/buhar/2-cikisli</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/buhar/dogalgazli-belgeli-onayli</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/buhar/60kw</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/buhar/30kw</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/paskar/isikli-balanserli-genis</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/paskar/kendinden-kazanli</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/paskar/isitmasiz</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/paskar/isikli-balanserli-kendinden-kazanli</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/paskar/isikli-balanserli-dar</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/transfer/20-20-gezer-kafa</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/transfer/20-20-doner-kafa</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/transfer/40-50-tas-yapistirma</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/cakim/motorlu1</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/cakim/motorlu2</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/cakim/elektrikli</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/dirtycleaners%2A/masa-tipi</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/dirtycleaners%2A/dar-tipi-klasik</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/silters/silter-supermini-1lt</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/silters/magma-3-5</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/silters/sprmn-2035-silter-super-mini</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/silters/sprmn-2005-silter-super-mini</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/silters/sprmn-2030-gazella-silter</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/silters/potent-fan-dar-masa-3-5</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/silters/sprmn-2036-3-5-lt</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/silters/silter-bitsy-minisilter-sm-bm-2035</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/transpalet/cift-siperli</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/transpalet/agir-hizmet-modeli</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/transpalet/plastik-tekne</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/transpalet/tekerlekli-hasir-tel-sepet</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/qualityco/ustten-isikli-egim-ayarli</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/qualityco/sabit-egimli</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/qualityco/sabit-egimli-ustten-isikli</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/others/yan-dikis-acma</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/others/pantolon-sisirme</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/others/cift-kafa-iplik-temizleme</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/others/kilcik</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/yedek/silter-sy-kf-3722y</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url></loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
    <loc>https://www.elitasmakina.com/product/yedek/buhar-kazanli-su-pompasi</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/yedek/silter-stb-200g</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/yedek/stb-295-gazella-slim</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/yedek/magma-buharli</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/yedek/leke-tabancasi</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/yedek/paskara-kare-fan-motoru</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
  <url>
    <loc>https://www.elitasmakina.com/product/yedek/kazanci-utu-selenoid-valf</loc>
    <lastmod>2023-05-21</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.8</priority>
  </url>
</urlset>`.trim(),
        {
            headers: {
                'Content-Type': 'application/xml'
            }
        }
    );
}